endpoint: http://jira
user: MJ093
editor: vi
browser: brave-browser

password-source: pass
password-name: addi/domain

custom-commands:
  - name: mine
    help: display issues assigned to me
    args:
      - name: PROJECT
        required: false
    script: |-
      [ -n {{args.PROJECT}} ] && QUERYPROJECT="and project = {{args.PROJECT}}"
      {{jira}} list --template mine --query "resolution = unresolved and assignee=currentuser() $QUERYPROJECT ORDER BY status asc, created" | \
               sed -e 's/To Do/1status/' -e 's/In Progress/2status/' -e 's/In Review/3status/' | \
               sort -b -t'|' -k 4 | \
               sed -e "s/1status/$(printf "\033[31mTo Do\033[0m")/" -e "s/2status/$(printf "\033[36mIn Progress\033[0m")/" -e "s/3status/$(printf "\033[32mIn Review\033[0m")/" -e "s/Martinez-Le_Ninan.Jean/Jean/g" | \
               column -t -s '|'

  - name: in-review
    help: transition issue to In Review
    args:
      - name: ISSUE
        required: true
    script: |-
      {{jira}} transition --noedit 'In Review' {{args.ISSUE}}

  - name: cal
    help: display this week calendar of worklogs
    args:
      - name: USER
        required: false
    script: |-
      USER="MJ093"
      [ -n {{args.User}} ] && USER="{{args.USER}}"
      ~/scripts/addi/jiraWorklogs.sh $USER | remind -c+2@1mb1 -w$(($(tput cols) * 7 / 5 + 5)) - $(date -d 'last monday -7 days' +'%d %b %Y')  | cut -d '|' -f 1-6 | cut -d '+' -f 1-6 | sed "s/\(\*\+\)/$(printf "\033[31m\\\1\033[0m")/g"

  - name: addwork
    help: add worklog at date $1 time $2 with issue $3 with current dir jira log
    args:
      - name: DATE
        help: relative number of days
        required: true
      - name: TIME
        help: hour time of the begining in 24h format
        required: true
      - name: DURATION
        help: jira notation of duration with {d,h,m}
        required: true
      - name: ISSUE
        required: true
    script: |-
      {{jira}} worklog add -S $(date -d "-{{args.DATE}} day" +%Y-%m-%dT{{args.TIME}}:00:00.000+0100) -T {{args.DURATION}} -m "$(< jira)" --noedit {{args.ISSUE}}

  - name: activ
    help: Print gitlab activity linked to account at relativ day $1
    args:
      - name: DATE
        help: relative number of days
        required: true
    script: |-
      curl -sH "Private-Token: $(pass addi/gitlab-token)" -X GET gitlab-srv01/api/v4/users/3/events\?action\=pushed\&after\=$(date -d "-$(({{args.DATE}} + 1)) day"  +%Y-%m-%d)\&before\=$(date -d "-$(({{args.DATE}} - 1)) day" +%Y-%m-%d) | jq -r '.[].push_data.commit_title'
